USB_VID = 0x0483
USB_PID = 0x5740
USB_PRODUCT = "STEVAL-FCU001V1"
USB_MANUFACTURER = "ST"

INTERNAL_FLASH_FILESYSTEM = 1

MCU_SERIES = F4
MCU_VARIANT = STM32F412Cx
MCU_PACKAGE = UFQFPN48

LD_COMMON = boards/common_default.ld
LD_FILE = boards/STM32F412_fs.ld

# Disable ulab as we're nearly out of space on this board due to
# INTERNAL_FLASH_FILESYSTEM.  It can probably be reenabled if we enable
# lto for this port, and if other stuff hasn't been added in the
# meantime
#CIRCUITPY_AESIO = 0
#CIRCUITPY_AUDIOCORE = 0
#CIRCUITPY_AUDIOPWMIO = 0
#CIRCUITPY_BLEIO_HCI = 0
#CIRCUITPY_BUSDEVICE = 0
#CIRCUITPY_BITMAPTOOLS = 0
#CIRCUITPY_FRAMEBUFFERIO = 0
#CIRCUITPY_GIFIO = 0
#CIRCUITPY_KEYPAD = 0
#CIRCUITPY_MIDI = 0
#CIRCUITPY_MSGPACK = 0
#CIRCUITPY_ULAB = 0
#CIRCUITPY_VECTORIO = 0
#
#SUPEROPT_GC = 0
#SUPEROPT_VM = 0
#
#OPTIMIZATION_FLAGS = -Os
#
